{
  imports = [
    users/admin
    users/akos
    modules/security/sops.nix
    modules/hardware/perifirals/keyboards/kanata/default.nix
    modules/hardware/perifirals/mice/razer.nix
    modules/virtualization/virtualbox.nix
    modules/virtualization/podman.nix
    modules/virtualization/docker.nix
    modules/virtualization/virt-manager.nix
    modules/virtualization/vmware.nix
    modules/dev/platformio.nix
    modules/fonts/nerdfonts.nix
    modules/wm/dwm.nix
    modules/wm/niri.nix
    modules/games/steam.nix
    modules/system/bluetooth.nix
    modules/system/sound.nix
    modules/system/locale.nix
    modules/system/binbash.nix
    modules/system/printing.nix
    modules/system/gpg.nix
    modules/networking/sshd.nix
    modules/networking/usbip.nix
    modules/networking/dnsmasq/default.nix
    modules/networking/airlab-vpn.nix
    modules/networking/tailscale.nix
    modules/networking/netbird.nix
    modules/nix/builders/airlab.nix
    modules/nix/builders/build-host.nix
    profiles/zroot.nix
    profiles/global.nix
    profiles/server.nix
  ];
}
