keys:
  - &akos01zfs age13g9ww6uvta3p5uqwy8ye03vl6cxtezdsfmw97kay8lgnwd7cwdxqugv3vl
  - &hp age1ldw6atyczam0z88m26myg0hlydqkxput7r22c5svtd503ts523kqhmmtug
  - &legion5 age1u57z2k07r7cajz0507z4tgltgq5jwt7dfaks0z7cdgnn7pvqkg2qzv4l7u
  - &akos01 age1lpxm6erm9xj0v4jph03gujcj0xzlgjl3h9pqwvtzl36hpl8gmu5qyujzfp
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *akos01zfs
      - *hp
      - *legion5
      - *akos01

