keys:
  - &hp age1ldw6atyczam0z88m26myg0hlydqkxput7r22c5svtd503ts523kqhmmtug
  - &legion5 age1u57z2k07r7cajz0507z4tgltgq5jwt7dfaks0z7cdgnn7pvqkg2qzv4l7u
  - &akos01 age19gyg7jg2pfw6zklt62uwmkxz4jcl7ltg855dlyja375kqqaq052qqyrwtk
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *hp
      - *legion5
      - *akos01

